spring:
  application:
    name: es-plus-test

# es-plus配置
#es-plus:
#  # es连接地址+端口 格式必须为ip:port,如果是集群则可用逗号隔开
#  address: 10.10.50.177:9200,10.10.50.178:9200,10.10.50.179:9200
#  #  address: 139.198.107.120:9200
#  # 默认为http
#  schema: http
#  # 如果无账号密码则可不配置此项
#  username: elastic
#  # 如果无账号密码则可不配置此项
#  password: Yhsl@123
#  global-config:
#    # 输出DSL日志
#    enable-dsl: true
#    document-config:
#      index-prefix: test_
#      key-type: auto
#      field-strategy: not_null
#      date-format: yyyy-MM-dd HH:mm:ss
#      map-underscore-to-camel-case: false

# es-plus配置
es-plus:
  dynamic:
    primary: master
    client:
      master:
        # es连接地址+端口 格式必须为ip:port,如果是集群则可用逗号隔开
        address: 10.10.50.177:9200,10.10.50.178:9200,10.10.50.179:9200
        # 默认为http
        schema: http
        # 如果无账号密码则可不配置此项
        username: elastic
        # 如果无账号密码则可不配置此项
        password: Yhsl@123
      localhost:
        # es连接地址+端口 格式必须为ip:port,如果是集群则可用逗号隔开
        address: 10.10.50.143:9200,10.10.50.144:9200,10.10.50.145:9200
        # 默认为http
        schema: http
    global-config:
      # 输出DSL日志
      enable-dsl: true
      document-config:
        index-prefix: test_
        key-type: auto
        field-strategy: not_null
        date-format: yyyy-MM-dd HH:mm:ss
        map-underscore-to-camel-case: false