spring:
  application:
    name: es-plus-example
# es-plus配置
es-plus:
  # 是否开启es-plus自动配置
  enable: true
  # es连接地址+端口 格式必须为ip:port,如果是集群则可用逗号隔开
#  address : 10.10.50.177:9200,10.10.50.178:9200,10.10.50.179:9200
  address : 139.198.107.120:9200
  # 默认为http
  schema: http
  # 如果无账号密码则可不配置此项
#  username: elastic
  # 如果无账号密码则可不配置此项
#  password: Yhsl@123
  global-config:
    # 输出日志
    log-enable: true
